% Generate PSF folder name
% ELi, 20220530
function PSFFolderName = PSFNameGenerator(PSFParameters)
switch PSFParameters.angDistParameters.scanningMode
    case 0 % self-determined
        PSFFolderName = ['PSF_',...
            PSFParameters.imagingMode,...
            '_',...
            'zoom',num2str(PSFParameters.EIParameters.zoomFactor),...
            'ca',num2str(PSFParameters.EIParameters.catchSize),...
            'up',num2str(PSFParameters.EIParameters.upSample),...
            'psf',num2str(PSFParameters.xysize),...
            '_',...
            num2str(PSFParameters.defocusLower),'-',num2str(PSFParameters.defocusInterval),'-',num2str(PSFParameters.defocusUpper),...
            '_',...
            'scanMode',...
            num2str(PSFParameters.angDistParameters.scanningMode),...
            '-',...
            datestr(now, 'YYYYmmDD_HHMMSS'),...
            '_',...
            'pup',PSFParameters.pupilPhaseSet,...
            '_',...
            'en',num2str(PSFParameters.energySet),...
            '_',...
            'K',num2str(PSFParameters.shiftKRange),...
            'bias',num2str(PSFParameters.shiftKBias),...
            ];
    case 1 % 'square'
        PSFFolderName = ['PSF_',...
            PSFParameters.imagingMode,...
            '_',...
            'zoom',num2str(PSFParameters.EIParameters.zoomFactor),...
            'ca',num2str(PSFParameters.EIParameters.catchSize),...
            'up',num2str(PSFParameters.EIParameters.upSample),...
            'psf',num2str(PSFParameters.xysize),...
            '_',...
            num2str(PSFParameters.defocusLower),'-',num2str(PSFParameters.defocusInterval),'-',num2str(PSFParameters.defocusUpper),...
            '_',...
            'scanMode',...
            num2str(PSFParameters.angDistParameters.scanningMode),...
            '_',...
            num2str(PSFParameters.angDistParameters.SamplingNumber_X),'x',num2str(PSFParameters.angDistParameters.SamplingNumber_Y),...
            '_',...
            'maxX',num2str(PSFParameters.angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(PSFParameters.angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(PSFParameters.angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(PSFParameters.angDistParameters.bias_Y,'%.1f'),...
            '_',...
            'pup',PSFParameters.pupilPhaseSet,...
            '_',...
            'en',num2str(PSFParameters.energySet),...
            '_',...
            'K',num2str(PSFParameters.shiftKRange),...
            'bias',num2str(PSFParameters.shiftKBias),...
            ];
    case 2 % 'circ'
        PSFFolderName = ['PSF_',...
            PSFParameters.imagingMode,...
            '_',...
            'zoom',num2str(PSFParameters.EIParameters.zoomFactor),...
            'ca',num2str(PSFParameters.EIParameters.catchSize),...
            'up',num2str(PSFParameters.EIParameters.upSample),...
            'psf',num2str(PSFParameters.xysize),...
            '_',...
            num2str(PSFParameters.defocusLower),'-',num2str(PSFParameters.defocusInterval),'-',num2str(PSFParameters.defocusUpper),...
            '_',...
            'scanMode',...
            num2str(PSFParameters.angDistParameters.scanningMode),...
            '_',...
            num2str(PSFParameters.angDistParameters.lowNA_rouNumber),...
            '-',num2str(PSFParameters.angDistParameters.lowNA_thetaNumberMin),...
            '-',num2str(PSFParameters.angDistParameters.lowNA_thetaNumberMax),...
            '_',...
            'maxX',num2str(PSFParameters.angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(PSFParameters.angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(PSFParameters.angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(PSFParameters.angDistParameters.bias_Y,'%.1f'),...
            '_',...
            'pup',PSFParameters.pupilPhaseSet,...
            '_',...
            'en',num2str(PSFParameters.energySet),...
            '_',...
            'K',num2str(PSFParameters.shiftKRange),...
            'bias',num2str(PSFParameters.shiftKBias),...
            ];
    case 3 % 'sunflower'
        PSFFolderName = ['PSF_',...
            PSFParameters.imagingMode,...
            '_',...
            'zoom',num2str(PSFParameters.EIParameters.zoomFactor),...
            'ca',num2str(PSFParameters.EIParameters.catchSize),...
            'up',num2str(PSFParameters.EIParameters.upSample),...
            'psf',num2str(PSFParameters.xysize),...
            '_',...
            num2str(PSFParameters.defocusLower),'-',num2str(PSFParameters.defocusInterval),'-',num2str(PSFParameters.defocusUpper),...
            '_',...
            'scanMode',...
            num2str(PSFParameters.angDistParameters.scanningMode),...
            '_',...
            num2str(PSFParameters.angDistParameters.NANums),...
            '_',...
            'maxX',num2str(PSFParameters.angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(PSFParameters.angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(PSFParameters.angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(PSFParameters.angDistParameters.bias_Y,'%.1f'),...
            '_',...
            'pup',PSFParameters.pupilPhaseSet,...
            '_',...
            'en',num2str(PSFParameters.energySet),...
            '_',...
            'K',num2str(PSFParameters.shiftKRange),...
            'bias',num2str(PSFParameters.shiftKBias),...
            ];
end
end