% Generate angle distribution filename according to certain rules
% ELiiiiiii, 20220530
function angDistSaveName = angDistNameGenerator(angDistParameters)
switch angDistParameters.scanningMode
    case 1 %'square'
        angDistSaveName = ['shiftInPupil_square',...
            '_',...
            num2str(angDistParameters.SamplingNumber_X),'x',num2str(angDistParameters.SamplingNumber_Y),...
            '_',...
            'maxX',num2str(angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(angDistParameters.bias_Y,'%.1f'),...
            '.mat',...
            ];
    case 2 %'circ'
        angDistSaveName = ['shiftInPupil_circ',...
            '_',...
            num2str(angDistParameters.lowNA_rouNumber),...
            '-',num2str(angDistParameters.lowNA_thetaNumberMin),...
            '-',num2str(angDistParameters.lowNA_thetaNumberMax),...
            '_',...
            'maxX',num2str(angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(angDistParameters.bias_Y,'%.1f'),...
            '.mat',...
            ];
    case 3 %'sunflower'
        angDistSaveName = ['shiftInPupil_sunflower',...
            '_',...
            num2str(angDistParameters.NANums),...
            '_',...
            'maxX',num2str(angDistParameters.Interval_X_Upper,'%.4f'),...
            'Y',num2str(angDistParameters.Interval_Y_Upper,'%.4f'),...
            'biasX',num2str(angDistParameters.bias_X,'%.1f'),...
            'Y',num2str(angDistParameters.bias_Y,'%.1f'),...
            '.mat',...
            ];
    otherwise
        error('Unrecognized scanningMode');
end
end