%Generate deconvolution folder name according to rules set by ELi in 20210624
%%ELi, 20210624
%%ELi, 20220531, add MC
function deconvFolderName = deconvNameGenerator(deconvOptions,PSFParameters)
deconvFolderName = ['deconv',...
    '_',...
    deconvOptions.solver,...
    '_',...
    'zoom',num2str(PSFParameters.EIParameters.zoomFactor),...
    'ca',num2str(PSFParameters.EIParameters.catchSize),...
    'up',num2str(PSFParameters.EIParameters.upSample),...
    '_',...
    num2str(PSFParameters.defocusLower),'-',num2str(PSFParameters.defocusInterval),'-',num2str(PSFParameters.defocusUpper),...
    '_',...
    'pup',PSFParameters.pupilPhaseSet,...
    '_',...
    'en',num2str(PSFParameters.energySet),...
    '_',...
    'K',num2str(PSFParameters.shiftKRange),...
    'bias',num2str(PSFParameters.shiftKBias),...
    '_',...
    'AO',num2str(deconvOptions.AO),...
    '_',...
    'EW',num2str(deconvOptions.equalWeight),...
    '_',...
    'mI',num2str(deconvOptions.maxIter),...
    '_',...
    'mC',num2str(deconvOptions.demotion),...
    '_',...
    'frames',num2str(deconvOptions.startFrame),'-',num2str(deconvOptions.step),'-',num2str(deconvOptions.endFrame),...
    ];
end